config/routes.rb
Rails.application.routes.draw do
  get 'messages/index'
  get 'messages/new'
  get 'messages/create'
  devise_for :users
  root "targets#index"
  resources :users,   only: [:edit, :update]
  resources :targets, only: [:index, :new, :create, :show] do
    collection do
      get 'search'
      get 'myindex'
      get 'allindex'
    end
  end
  resources :matchs do
    collection do
      get 'match_target', to: 'matchs#match_target'
      get 'done',         to: 'matchs#done'
    end
  end
  resources :messages, only: [:index, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/match.rb
class Match < ApplicationRecord
  # Validations

  # Associations
  belongs_to :user
  belongs_to :target
end

app/models/message.rb
class Message < ApplicationRecord
  # Validations
  validates :message, presence: true

  # Associations
  belongs_to :user
  belongs_to :match
end

app/models/target.rb
class Target < ApplicationRecord
  # Validations
  validates :target,      presence: true
  validates :explanation, presence: true
  validates :limit,       presence: true
  validates :status,      presence: true

  # Associations
  belongs_to :user
  has_many   :matchs
  has_many   :messages

  def self.search(search)
    return Target.all unless search
    Target.where('target LIKE(?)', "%#{search}%")
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise    :database_authenticatable, :registerable,
            :recoverable, :rememberable, :validatable

  # Validations
  validates :nickname, presence: true, uniqueness: true
  validates :email,    presence: true, uniqueness: true
  validates :gender,   presence: true

  # Associations
  has_many :targets
  has_many :matchs
  has_many :messages

  mount_uploader :icon, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :gender, :profile, :icon])
  end
end

app/controllers/matchs_controller.rb
class MatchsController < ApplicationController
  def match_target
    @target = Target.find(params[:target_id])
    @match = Match.new
  end

  def done
    @target = Target.find(params[:target_id])
    @target.status = "Pare"
    @target.save
    Match.create(target_id: params[:target_id], user_id: current_user.id)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
before_action :set_match

  def index
    @message = Message.new
    @messages = Message.where(match_id: @match).includes(:user)
  end

  def create
    @message = Message.new(message_params)
    if @message.save!
      redirect_to messages_path(match_id: @match), notice: 'メッセージが送信されました'
    else
      flash.now[:alert] = 'メッセージを入力してください。'
      render :index
    end
  end

  private
  def message_params
    params.require(:message,).permit(:message).merge(match_id: params[:match_id], user_id: current_user.id)
  end

  def set_match
    @match = Match.find(params[:match_id])
  end
end

app/controllers/targets_controller.rb
class TargetsController < ApplicationController
  before_action :set_target, only: [:show, :edit, :update]

  def index
    @mytargets = Target.where(user_id: current_user.id).limit(5).order('id DESC')
    @alltargets = Target.all.limit(5).order('id DESC').where.not(user_id: current_user.id)
  end

  def myindex
    @targets = Target.where(user_id: current_user.id)
  end

  def allindex
    @targets = Target.all.where.not(user_id: current_user.id)
  end

  def new
    @target = Target.new
  end

  def create
    @target = Target.new(target_params)
    @target.status = "No Pare"
    if @target.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
  end

  def search
    @targets = Target.search(params[:keyword]).where.not(user_id: current_user.id)
  end

  def edit
  end

  def update
  end

  private
  def target_params
    params.require(:target).permit(:target, :explanation, :limit).merge(user_id: current_user.id)
  end

  def set_target
    @target = Target.find(params[:id])
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # GET /resource/sign_up
  def new
  end

  # POST /resource
  def create
    super
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :email, :gender, :profile, :icon)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Parecommit
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application'
    = javascript_pack_tag 'application'
  %body
    = render 'layouts/notifications'
    = yield

app/views/layouts/message.html.haml
-# チャット画面ですね

.main
  .header
    .header-match
      .header-match_name
        katou hanako
      .header-match_target
        .header-match_target-name
          プログラミング
        .header-match_target-limit
          2020/5/16
  .body
    .body-list
      .list-match_icon
        .list-match_icon-image
          aaa
      .list-match_text
        私はRailsに取り組みます。
    .body-list
      .list-match_icon
        .list-match_icon-image
          bbb
      .list-match_text
        私はJSに取り組みます。
  .form
    .form-list
      .input-text
        ccc
      .input-support
        sss
      .input-button
        Send

app/views/matchs/done.html.haml
= render "share/title_bar"
.wrapper
  = render "share/side_bar"
  .main
    .match
      .match-result
        .match-result__box
          .match-result__box-text
            pareを結成しました。

app/views/matchs/new.html.haml
= render "share/title_bar"
.wrapper
  = render "share/side_bar"
  .main
    .target
      .search-name
        プログラミング
      .target-list
        .target-list_box
          .target-list_box_icon
            .target-list_box_icon-image
              ccc
          .profile
            .profile-name
              tanaka hiroshi
            .profile-detele
              .profile-detele_limit
                2020/12/31
              .profile-detele_gender
                男
            .profile-message
              一緒に頑張りましょう！
          .match
            .match-button
              Pare
        .target-list_box
          .target-list_box_icon
            .target-list_box_icon-image
              ddd
          .profile
            .profile-name
              endo shoko
            .profile-detele
              .profile-detele_limit
                2020/5/31
              .profile-detele_gender
                女
            .profile-message
              目指せ就職！
          .match
            .match-button
              Pare

app/views/messages/_message.html.haml
.message
  .upper-message
    .upper-message__user
      = message.user.nickname
    .upper-message__date
      = message.created_at.strftime("%Y年%m月%d日 %H時%M分")
  .lower-message
    .lower-message__content
      = message.message

app/views/messages/index.html.haml
= render "share/title_bar"
.wrapper
  = render "share/side_bar"
  .main
    .content
      .message-header
        .message-header__box
          .message-header__box-title
            目標名 : 
          .message-header__box-content
            = @match.target.target
      = render partial: 'message', collection: @messages
    = form_with(model:@message, local: true, class: "message-form") do |form|
      = form.text_field  :message, class: "message-form__input"
      = hidden_field_tag :match_id, params[:match_id], class: "message-form__id"
      = form.submit "Send", class: "message-form__button"

app/views/share/_side_bar.html.haml
.side-bar
  .header
    .char
      .char-box
        .char-box_icon
          = image_tag "#{current_user.icon}", width:"150px", class:"char-box_icon-image"
        .char-box_name
          .char-box_name_title
            = current_user.nickname
          .char-box_name_edit
            = link_to edit_user_path(current_user) do
              = icon('fas', 'cog', class: 'icon')
        .char-box_logout
          = link_to "ログアウト", destroy_user_session_path, method: :delete
  .side-main
    - current_user.matchs.each do |match|
      .match-list
        .match-box
          .match-box_icon
            = image_tag "#{match.target.user.icon}", width:"150px", class:"match-box_icon-image"
          .match-box_name
            = link_to messages_path(match_id: match) do
              = match.target.target
    - current_user.targets.each do |target|
      - target.matchs.each do |match|
        .match-list
          .match-box
            .match-box_icon
              = image_tag "#{match.user.icon}", width:"150px", class:"match-box_icon-image"
            .match-box_name
              = link_to messages_path(match_id: match) do
                = match.target.target

app/views/share/_title_bar.html.haml
.bar
  = link_to "PareComit", "/", class: "bar-title"

app/views/targets/_main_target.html.haml
.main
  .target
    .target-new
      目標を設定
      =link_to new_target_path do
        .target-new__title
          Target Set
    = form_with(url: search_targets_path, local: true, method: :get, class: "search-form") do |form|
      .search-form__title
        目標を共有、Pareを作成
      = form.text_field :keyword, placeholder: "目標を検索する", class: "search-form__input"
      = form.submit "Search", class: "search-form__button"
    .target-list
      .target-list__title
        目標リスト
        .target-mylist
          .target-mylist__title
            自分の目標(新着順)
          - @mytargets.each do |target|
            .target-mylist__box
              .target-mylist__box-name
                = link_to target_path(target.id) do
                  = target.target
          .target-mylist__plus
            = link_to myindex_targets_path do
              more
        .target-all
          .target-all__title
            みんなの目標(新着順)
          - @alltargets.each do |target|
            .target-all__box
              .target-all__box-name
                = link_to target_path(target.id) do
                  = target.target
          .target-mylist__plus
            = link_to allindex_targets_path do
              more

app/views/targets/allindex.html.haml
= render "share/title_bar"
.wrapper
  = render "share/side_bar"
  .main
    .target
      .target-name
        = "#{current_user.nickname}"
      .targets-list
        - @targets.each do |target|
          .target-list_box
            = image_tag "#{target.user.icon}", width:"150px", class:"search-list_box_icon"
            .profile
              .profile-name
                = target.user.nickname
              .profile-detele
                .profile-detele_limit
                  = target.limit
                .profile-detele_gender
                  = target.user.gender
              .profile-message
                = target.explanation
            .target-target
              = link_to target_path(target.id) do
                = target.target

app/views/targets/index.html.haml
= render "share/title_bar"
.wrapper
  = render "share/side_bar"
  = render "main_target"

app/views/targets/myindex.html.haml
= render "share/title_bar"
.wrapper
  = render "share/side_bar"
  .main
    .target
      .target-name
        = "#{current_user.nickname}"
      .targets-list
        - @targets.each do |target|
          .target-list_box
            = image_tag "#{target.user.icon}", width:"150px", class:"search-list_box_icon"
            .profile
              .profile-name
                = target.user.nickname
              .profile-detele
                .profile-detele_limit
                  = target.limit
                .profile-detele_gender
                  = target.user.gender
              .profile-message
                = target.explanation
            .target-target
              = link_to target_path(target.id) do
                = target.target

app/views/targets/new.html.haml
= render "share/title_bar"
.wrapper
  = render "share/side_bar"
  .main
    .new
      = form_with model: @target, local: true do |form|
        .target-box
          .target-box__title
            .target-box__title-text
              目標名
            .target-box__title-required
              必須
          .target-box__field
            = form.text_field :target, placeholder: "40文字まで"
        .target-box
          .target-box__title
            .target-box__title-text
              目標への意気込み
            .target-box__title-required
              必須
          .target-box__area
            = form.text_area :explanation, placeholder: "目標の説明（必須 1,000文字以内）\n（目標に対しての意気込みや自分の中の達成したい内容の詳細など）", rows: "7"
        .target-box
          .target-box__title
            .target-box__title-text
              目標日
            .target-box__title-required
              必須
          .target-box__field
            = form.date_field :limit
        .target-button
          .target-button__decision
            = form.submit "Create"
          .target-button__back
            =link_to "Back", '/'

app/views/targets/search.html.haml
= render "share/title_bar"
.wrapper
  = render "share/side_bar"
  .main
    .search
      .search-name
        = "#{params[:keyword]}"
      .search-list
        - @targets.each do |target|
          - if target.status == "No Pare"
            .search-list_box
              = image_tag "#{target.user.icon}", width:"150px", class:"search-list_box_icon"
              .profile
                .profile-name
                  = target.user.nickname
                .profile-detele
                  .profile-detele_limit
                    = target.limit
                  .profile-detele_gender
                    = target.user.gender
                .profile-message
                  = target.explanation
              .search-target
                = link_to target_path(target.id) do
                  .search-target__button
                    Pare

app/views/targets/show.html.haml
= render "share/title_bar"
.wrapper
  = render "share/side_bar"
  .main
    .show
      .show-main
        .target-box
          .target-box__title
            .target-box__title-text
              ユーザー名
          .target-box__field
            = @target.user.nickname
        .target-box
          .target-box__title
            .target-box__title-text
              目標名
          .target-box__field
            = @target.target
        .target-box
          .target-box__title
            .target-box__title-text
              目標への意気込み
          .target-box__area
            = @target.explanation
        .target-box
          .target-box__title
            .target-box__title-text
              目標日
          .target-box__field
            = @target.limit
        - if current_user.id == @target.user_id
          .target-button
            .target-button__decision
              = link_to "Edit", "#"
            .target-button__back
              = link_to "Back", '/'
        - else
          - if @target.status == "No Pare"
            .target-button
              .target-button__decision
                = link_to "Pare", done_matchs_path(target_id: @target)
              .target-button__back
                = link_to "Back", '/'
          - else
            .target-button
              .target-button__decision
                Pare結成済
              .target-button__back
                = link_to "Back", '/'

app/views/users/edit.html.haml
= render "share/title_bar"
.wrapper
  .user
    .header
      .header-title
        Edit
    .main
      .main-box
        = form_for(current_user) do |f|
          .field
            .main-box_icon
              = f.file_field :icon, autofocus: true, autocomplete: "icon"
            .main-box_form
              .main-box_form-title
                mail :
              .main-box_form-input
                = f.email_field :email, autofocus: true, autocomplete: "email"
            .main-box_form
              .main-box_form-title
                nickname :
              .main-box_form-input
                = f.text_field :nickname, autofocus: true, autocomplete: "nickname"
            .main-box_form
              .main-box_form-title
                gender :
              .main-box_form-input
                = f.text_field :gender, autofocus: true, autocomplete: "gender"
            .main-box_form
              .main-box_form-title
                profile :
              .main-box_form-input
                = f.text_area :profile, placeholder: "自分について一言！", rows: "7"
          .actions
            .actions-buttom
              .actions-buttom__decision
                = f.submit "Edit"
              .actions-buttom__back
                = link_to "Back", '/'

app/views/users/shared/_error_messages.html.haml
- if resource.errors.any?
  #error_explanation
    %h2
      = I18n.t("errors.messages.not_saved",                 |
        count: resource.errors.count,                       |
        resource: resource.class.model_name.human.downcase) |
    %ul
      - resource.errors.full_messages.each do |message|
        %li= message

app/views/users/shared/_links.html.haml
- if controller_name != 'sessions'
  = link_to "Log in", new_session_path(resource_name)
  %br/
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  %br/
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  %br/
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  %br/
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider)
    %br/